# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'BCLRingSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
  pod 'QMUIKit','4.8.0'
  
  pod 'Foil', '~> 5.1.2'
  pod 'iOSDFULibrary'
  pod 'RxSwift', '~> 6.9.0'
  pod 'SwiftDate'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'Zip'

  # Pods for BCLRingSDKDemo

end
